export function buildCatalogue(d) {
  if (!d) return [];

  // Construit une série en combinant historique statique + valeur actuelle
  const serie = (hist, current) => {
    const s = [...hist];
    if (current != null && !isNaN(parseFloat(current)) && s[s.length-1] !== parseFloat(current))
      s.push(parseFloat(current));
    return s;
  };

  return [
    // === CONJONCTURE ===
    { id: 'pib_trim', categorie: '📈 Conjoncture', label: 'PIB trimestriel',
      getValue: d => d.pib?.croissance_trim_actuel != null ? `+${d.pib.croissance_trim_actuel}%` : '—',
      getSparkline: d => { const h = d.pib?.evolution?.map(e=>e.croissance)||[]; return h.length>=4 ? h.slice(-12) : serie([-0.1,0.2,0.4,0.5,0.2,0.1,0.5,0.3,0.4,0.1,0.3], d.pib?.croissance_trim_actuel); },
      getStatus: d => (d.pib?.croissance_trim_actuel||0) >= 0 ? 'good' : 'bad',
      tooltip: 'Croissance T/T-1 du PIB volume' },
    { id: 'climat_affaires', categorie: '📈 Conjoncture', label: 'Climat affaires',
      getValue: d => d.indicateurs_cles?.climat_affaires ?? d.climat_affaires?.valeur_actuelle ?? '—',
      getSparkline: d => {
        const h = (d.climat_affaires?.evolution || d.conjoncture?.climat_affaires?.evolution || []).map(e => e.climat);
        return h.length >= 4 ? h.slice(-12) : serie([100,99,97,94,97,95,100,97,96,99,97], d.indicateurs_cles?.climat_affaires);
      },
      getStatus: () => 'neutral',
      tooltip: 'Indice INSEE (100 = moyenne long terme)' },
    { id: 'confiance_menages', categorie: '📈 Conjoncture', label: 'Confiance ménages',
      getValue: d => d.climat_affaires?.confiance_menages ?? d.conjoncture?.climat_affaires?.confiance_menages ?? '—',
      getSparkline: d => {
        const h = (d.climat_affaires?.evolution || d.conjoncture?.climat_affaires?.evolution || []).map(e => e.menages);
        return h.length >= 4 ? h.slice(-12) : serie([91,90,91,93,92,91,89,90,90,91,91], d.climat_affaires?.confiance_menages);
      },
      getStatus: d => ((d.climat_affaires?.confiance_menages || d.conjoncture?.climat_affaires?.confiance_menages || 0)) >= 100 ? 'good' : 'warning',
      tooltip: 'Indicateur de confiance des ménages INSEE' },
    { id: 'defaillances', categorie: '📈 Conjoncture', label: 'Défaillances',
      getValue: d => d.indicateurs_cles?.defaillances_12m ? `${(d.indicateurs_cles.defaillances_12m/1000).toFixed(1)}k` : '—',
      getSparkline: d => { const h = d.conjoncture?.defaillances?.evolution?.map(e=>e.cumul)||[]; const actuel=d.indicateurs_cles?.defaillances_12m; return h.length>=4 ? h.slice(-12) : serie([42000,47000,51000,55000,57500,60000,63500,66000,66500,67000,67600], actuel); },
      getStatus: () => 'bad',
      tooltip: 'Défaillances d\'entreprises sur 12 mois', invertTrend: true },

    // === EMPLOI ===
    { id: 'chomage', categorie: '👥 Emploi', label: 'Chômage',
      getValue: d => d.indicateurs_cles?.taux_chomage_actuel != null ? `${d.indicateurs_cles.taux_chomage_actuel}%` : '—',
      getSparkline: d => { const h = d.chomage?.map(c=>c.taux)||[]; return h.length>=4 ? h.slice(-12) : serie([7.1,7.2,7.4,7.5,7.5,7.3,7.4,7.3,7.4,7.5,7.7], d.indicateurs_cles?.taux_chomage_actuel); },
      getStatus: d => (d.indicateurs_cles?.taux_chomage_actuel||10) < 7.5 ? 'good' : 'warning',
      tooltip: 'Taux de chômage BIT France métropolitaine', invertTrend: true },
    { id: 'chomage_jeunes', categorie: '👥 Emploi', label: 'Chômage jeunes',
      getValue: d => { const last = d.chomage?.slice(-1)[0]; return last ? `${last.jeunes}%` : '—'; },
      getSparkline: d => { const h = d.chomage?.map(c=>c.jeunes)||[]; return h.length>=4 ? h.slice(-12) : serie([17.5,17.0,17.6,17.6,18.1,17.7,18.3,19.0,18.5,18.8,19.2], null); },
      getStatus: () => 'bad',
      tooltip: 'Taux de chômage des moins de 25 ans', invertTrend: true },
    { id: 'emploi_seniors', categorie: '👥 Emploi', label: 'Emploi seniors',
      getValue: d => { const last = d.emploi_seniors?.slice(-1)[0]; return last ? `${last.taux}%` : '—'; },
      getSparkline: d => { const h = d.emploi_seniors?.map(e=>e.taux)||[]; return h.length>=4 ? h.slice(-12) : serie([56.5,57.0,57.5,58.4,59.0,59.6,60.2,60.4,60.8,61.1,61.5], null); },
      getStatus: () => 'neutral',
      tooltip: 'Taux d\'emploi des 55-64 ans' },

    // === SALAIRES ===
    { id: 'smic_net', categorie: '💵 Salaires', label: 'SMIC net',
      getValue: d => d.indicateurs_cles?.smic_net ? `${d.indicateurs_cles.smic_net}€` : '—',
      getSparkline: d => serie([1185,1204,1219,1231,1258,1302,1329,1353,1383,1399,1427,1437], d.indicateurs_cles?.smic_net),
      getStatus: () => 'neutral',
      tooltip: 'SMIC mensuel net en vigueur' },
    { id: 'inflation', categorie: '💵 Salaires', label: 'Inflation',
      getValue: d => d.indicateurs_cles?.inflation_annuelle != null ? `${d.indicateurs_cles.inflation_annuelle}%` : '—',
      getSparkline: d => { const h = d.inflation_annuelle?.map(e=>e.inflation)||[]; return h.length>=4 ? h.slice(-12) : serie([0.5,1.6,5.2,4.9,4.0,2.3,1.8,1.5,1.2,1.0,0.9], d.indicateurs_cles?.inflation_annuelle); },
      getStatus: d => (d.indicateurs_cles?.inflation_annuelle||5) < 2 ? 'good' : 'warning',
      tooltip: 'Glissement annuel de l\'IPC', invertTrend: true },
    { id: 'ecart_hf', categorie: '💵 Salaires', label: 'Écart H/F',
      getValue: d => d.ecart_hf?.ecart_global ? `${d.ecart_hf.ecart_global}%` : '—',
      getSparkline: d => { const h = d.ecart_hf?.evolution?.map(e=>e.ecart)||[]; return h.length>=4 ? h : serie([18.4,16.6,16.1,15.5,14.9,14.2,14.0,14.0], d.ecart_hf?.ecart_eqtp); },
      getStatus: () => 'bad',
      tooltip: 'Écart salarial global hommes/femmes', invertTrend: true },
    { id: 'salaire_median', categorie: '💵 Salaires', label: 'Salaire médian',
      getValue: d => d.salaire_median?.montant_2024 ? `${d.salaire_median.montant_2024}€` : '—',
      getSparkline: d => { const h = d.salaire_median?.evolution?.map(e=>e.montant)||[]; return h.length>=4 ? h : serie([1800,1850,1900,1940,1960,2010,2090,2091], d.salaire_median?.montant_2024); },
      getStatus: () => 'neutral',
      tooltip: 'Salaire médian net mensuel' },

    // === CONDITIONS DE VIE ===
    { id: 'irl', categorie: '🏠 Conditions de vie', label: 'IRL (loyers)',
      getValue: d => d.irl?.glissement_annuel != null ? `+${d.irl.glissement_annuel}%` : '—',
      getSparkline: d => { const h = d.irl?.evolution?.map(e=>e.glissement)||[]; return h.length>=4 ? h.slice(-12) : serie([0.9,2.48,3.60,3.49,3.50,3.49,3.50,3.26,2.47,1.82,1.40], d.irl?.glissement_annuel); },
      getStatus: d => (d.irl?.glissement_annuel||5) < 2 ? 'good' : 'warning',
      tooltip: 'Glissement annuel de l\'Indice de Référence des Loyers', invertTrend: true },
    { id: 'gazole', categorie: '🏠 Conditions de vie', label: 'Gazole',
      getValue: d => d.carburants?.gazole?.prix ? `${d.carburants.gazole.prix}€/L` : '—',
      getSparkline: d => { const h = d.carburants?.evolution?.map(e=>e.gazole)||[]; return h.length>=4 ? h : serie([1.85,1.78,1.72,1.88,1.72,1.75,1.68,1.62,1.65,1.60,1.58], d.carburants?.gazole?.prix); },
      getStatus: d => (d.carburants?.gazole?.variation_an||0) < 0 ? 'good' : 'warning',
      tooltip: 'Prix moyen du gazole en France', invertTrend: true },
    { id: 'sp95', categorie: '🏠 Conditions de vie', label: 'SP95',
      getValue: d => d.carburants?.sp95?.prix ? `${d.carburants.sp95.prix}€/L` : '—',
      getSparkline: d => { const h = d.carburants?.evolution?.map(e=>e.sp95)||[]; return h.length>=4 ? h : serie([1.82,1.88,1.85,1.92,1.78,1.82,1.75,1.72,1.78,1.74,1.70], d.carburants?.sp95?.prix); },
      getStatus: d => (d.carburants?.sp95?.variation_an||0) < 0 ? 'good' : 'warning',
      tooltip: 'Prix moyen du SP95 en France', invertTrend: true },

    // === MARCHÉS FINANCIERS ===
    { id: 'oat_10ans', categorie: '💹 Marchés financiers', label: 'OAT 10 ans',
      getValue: d => d.marches_financiers?.oat_10ans?.valeur != null ? `${d.marches_financiers.oat_10ans.valeur}%` : '—',
      getSparkline: d => d.marches_financiers?.oat_10ans?.historique?.slice(-20)?.map(p=>p.valeur) || serie([0.13,-0.15,0.04,1.73,3.12,2.98,3.10,3.025], d.marches_financiers?.oat_10ans?.valeur),
      getStatus: () => 'neutral',
      tooltip: 'Taux de l\'OAT française à 10 ans' },
    { id: 'cac40', categorie: '💹 Marchés financiers', label: 'CAC 40',
      getValue: d => d.marches_financiers?.cac40?.valeur != null ? d.marches_financiers.cac40.valeur.toLocaleString('fr-FR') : '—',
      getSparkline: d => d.marches_financiers?.cac40?.historique?.slice(-20)?.map(p => p.valeur),
      getStatus: d => (d.marches_financiers?.cac40?.variations?.jour||0) >= 0 ? 'good' : 'bad',
      tooltip: 'Indice CAC 40 (clôture)' },
    { id: 'eurusd', categorie: '💹 Marchés financiers', label: 'EUR/USD',
      getValue: d => d.marches_financiers?.eurusd?.valeur ?? '—',
      getSparkline: d => d.marches_financiers?.eurusd?.historique?.slice(-20)?.map(p => p.valeur),
      getStatus: () => 'neutral',
      tooltip: 'Taux de change Euro / Dollar' },
    { id: 'brent', categorie: '💹 Marchés financiers', label: 'Brent',
      getValue: d => d.marches_financiers?.petrole_brent?.valeur != null ? `${d.marches_financiers.petrole_brent.valeur}$` : '—',
      getSparkline: d => d.marches_financiers?.petrole_brent?.historique?.slice(-20)?.map(p => p.valeur),
      getStatus: d => (d.marches_financiers?.petrole_brent?.variations?.jour||0) < 0 ? 'good' : 'warning',
      tooltip: 'Prix du Brent en USD/baril', invertTrend: true },
    { id: 'or', categorie: '💹 Marchés financiers', label: 'Or',
      getValue: d => d.marches_financiers?.or?.valeur != null ? `${d.marches_financiers.or.valeur.toLocaleString('fr-FR')}$` : '—',
      getSparkline: d => d.marches_financiers?.or?.historique?.slice(-20)?.map(p => p.valeur),
      getStatus: () => 'neutral',
      tooltip: 'Prix de l\'or en USD/once' },
    { id: 'gaz_naturel', categorie: '💹 Marchés financiers', label: 'Gaz TTF',
      getValue: d => d.marches_financiers?.gaz_naturel?.valeur != null ? `${d.marches_financiers.gaz_naturel.valeur}` : '—',
      getSparkline: d => d.marches_financiers?.gaz_naturel?.historique?.slice(-20)?.map(p => p.valeur),
      getStatus: d => (d.marches_financiers?.gaz_naturel?.variations?.jour||0) < 0 ? 'good' : 'warning',
      tooltip: 'Prix du gaz naturel TTF européen', invertTrend: true },
    { id: 'ble', categorie: '💹 Marchés financiers', label: 'Blé',
      getValue: d => d.marches_financiers?.ble?.valeur != null ? `${d.marches_financiers.ble.valeur}` : '—',
      getSparkline: d => d.marches_financiers?.ble?.historique?.slice(-20)?.map(p => p.valeur),
      getStatus: () => 'neutral',
      tooltip: 'Prix du blé en cents/boisseau' },
    { id: 'lme_cuivre', categorie: '💹 Marchés financiers', label: 'Cuivre LME',
      getValue: d => d.marches_financiers?.lme_cuivre?.valeur != null ? `${d.marches_financiers.lme_cuivre.valeur}` : '—',
      getSparkline: d => d.marches_financiers?.lme_cuivre?.historique?.slice(-20)?.map(p => p.valeur),
      getStatus: () => 'neutral',
      tooltip: 'Prix du cuivre LME en cts/lb' },
    { id: 'lme_aluminium', categorie: '💹 Marchés financiers', label: 'Aluminium LME',
      getValue: d => d.marches_financiers?.lme_aluminium?.valeur != null ? `${d.marches_financiers.lme_aluminium.valeur}` : '—',
      getSparkline: d => d.marches_financiers?.lme_aluminium?.historique?.slice(-20)?.map(p => p.valeur),
      getStatus: () => 'neutral',
      tooltip: 'Prix de l\'aluminium LME en cts/lb' },
    { id: 'lme_zinc', categorie: '💹 Marchés financiers', label: 'Zinc LME',
      getValue: d => d.marches_financiers?.lme_zinc?.valeur != null ? `${d.marches_financiers.lme_zinc.valeur.toLocaleString('fr-FR')}` : '—',
      getSparkline: d => d.marches_financiers?.lme_zinc?.historique?.slice(-20)?.map(p => p.valeur),
      getStatus: () => 'neutral',
      tooltip: 'Prix du zinc LME en $/t' },
    { id: 'lme_nickel', categorie: '💹 Marchés financiers', label: 'Nickel LME',
      getValue: d => d.marches_financiers?.lme_nickel?.valeur != null ? `${d.marches_financiers.lme_nickel.valeur.toLocaleString('fr-FR')}` : '—',
      getSparkline: d => d.marches_financiers?.lme_nickel?.historique?.slice(-20)?.map(p => p.valeur),
      getStatus: () => 'neutral',
      tooltip: 'Prix du nickel LME en $/t' },

    // === TRAVAIL ===
    { id: 'teletravail', categorie: '⚙️ Travail', label: 'Télétravail',
      getValue: d => d.temps_travail?.teletravail?.taux_salaries != null ? `${d.temps_travail.teletravail.taux_salaries}%` : '—',
      getSparkline: d => serie([8,10,12,15,28,27,26,26,26,26], d.temps_travail?.teletravail?.taux_salaries),
      getStatus: () => 'neutral',
      tooltip: '% de salariés pratiquant le télétravail' },
    { id: 'temps_partiel', categorie: '⚙️ Travail', label: 'Temps partiel',
      getValue: d => d.temps_travail?.temps_partiel?.taux_global_pct != null ? `${d.temps_travail.temps_partiel.taux_global_pct}%` : '—',
      getSparkline: d => serie([18.6,18.5,18.4,18.2,18.1,17.9,17.8,17.5,17.4,17.3], d.temps_travail?.temps_partiel?.taux_global_pct),
      getStatus: () => 'neutral',
      tooltip: 'Taux de temps partiel global' },

    // === POUVOIR D'ACHAT ===
    { id: 'taux_effort_logement', categorie: '💰 Pouvoir d\'achat', label: 'Effort logement',
      getValue: d => d.taux_effort?.par_statut?.[0]?.taux_median != null ? `${d.taux_effort.par_statut[0].taux_median}%` : '—',
      getSparkline: d => { const h = d.taux_effort?.evolution?.map(e=>e.locataires_libre)||[]; return h.length>=4 ? h : serie([23.8,25.2,27.0,28.6,28.6,29.0,29.6], d.taux_effort?.par_statut?.[0]?.taux_median); },
      getStatus: () => 'warning',
      tooltip: 'Taux d\'effort médian locataires secteur libre', invertTrend: true },
    { id: 'taux_immo', categorie: '💰 Pouvoir d\'achat', label: 'Taux immo',
      getValue: d => d.marches_financiers?.taux_immobilier?.valeur != null ? `${d.marches_financiers.taux_immobilier.valeur}%` : '—',
      getSparkline: d => { const h = d.marches_financiers?.taux_immobilier?.historique?.map(p=>p.valeur)||[]; return h.length>=4 ? h.slice(-12) : serie([1.12,1.52,2.25,3.04,3.83,4.22,4.17,3.66,3.30,3.17,3.10], d.marches_financiers?.taux_immobilier?.valeur); },
      getStatus: d => (d.marches_financiers?.taux_immobilier?.valeur||4) < 3 ? 'good' : 'warning',
      tooltip: 'Taux moyen des crédits immobiliers', invertTrend: true },
  ];
}
